# Generated by Django 5.1.6 on 2025-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_url', models.TextField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('available_on', models.CharField(blank=True, max_length=255, null=True)),
                ('available_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_1', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_2', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_3', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_4', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_5', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
